"""OpenCode prompts package — re-exports from opencode.py for backward compatibility."""

from .opencode import (
    OPENCODE_CODING_GUIDELINES,
    OPENCODE_CODE_REFS,
    OPENCODE_IDENTITY,
    OPENCODE_OBJECTIVITY,
    OPENCODE_PROMPTS,
    OPENCODE_STYLE,
    OPENCODE_TASK_MANAGEMENT,
    OPENCODE_TOOL_USAGE,
    OPENCODE_WORKFLOW,
)

__all__ = [
    "OPENCODE_PROMPTS",
    "OPENCODE_IDENTITY",
    "OPENCODE_STYLE",
    "OPENCODE_OBJECTIVITY",
    "OPENCODE_CODING_GUIDELINES",
    "OPENCODE_TOOL_USAGE",
    "OPENCODE_TASK_MANAGEMENT",
    "OPENCODE_CODE_REFS",
    "OPENCODE_WORKFLOW",
]
