"""Hermes prompts package — re-exports from hermes.py."""

from .hermes import (
    HERMES_BASE_PROMPT,
    HERMES_CONTEXT_FILES,
    HERMES_EXECUTION_DISCIPLINE,
    HERMES_IDENTITY,
    HERMES_MEMORY_GUIDANCE,
    HERMES_PROACTIVENESS,
    HERMES_SESSION_SEARCH,
    HERMES_SKILLS_GUIDANCE,
    HERMES_STYLE,
    HERMES_TOOL_USE_ENFORCEMENT,
)

__all__ = [
    "HERMES_IDENTITY",
    "HERMES_BASE_PROMPT",
    "HERMES_TOOL_USE_ENFORCEMENT",
    "HERMES_EXECUTION_DISCIPLINE",
    "HERMES_MEMORY_GUIDANCE",
    "HERMES_SKILLS_GUIDANCE",
    "HERMES_SESSION_SEARCH",
    "HERMES_STYLE",
    "HERMES_PROACTIVENESS",
    "HERMES_CONTEXT_FILES",
]
