"""Codex system prompts — sandbox, approval, coding guidelines, workflow."""

from extensions.prompts.codex.codex import (
    APPROVAL_NEVER,
    APPROVAL_ON_REQUEST,
    APPROVAL_POLICIES,
    APPROVAL_UNLESS_TRUSTED,
    CODEX_BASE_PROMPT,
    CODEX_CODING_GUIDELINES,
    CODEX_ENVIRONMENT_TEMPLATE,
    CODEX_IDENTITY,
    CODEX_TOOL_USAGE,
    CODEX_WORKFLOW,
    SANDBOX_DANGER_FULL_ACCESS,
    SANDBOX_MODES,
    SANDBOX_READ_ONLY,
    SANDBOX_WORKSPACE_WRITE,
)

__all__ = [
    "CODEX_IDENTITY",
    "CODEX_BASE_PROMPT",
    "SANDBOX_READ_ONLY",
    "SANDBOX_WORKSPACE_WRITE",
    "SANDBOX_DANGER_FULL_ACCESS",
    "SANDBOX_MODES",
    "APPROVAL_UNLESS_TRUSTED",
    "APPROVAL_ON_REQUEST",
    "APPROVAL_NEVER",
    "APPROVAL_POLICIES",
    "CODEX_CODING_GUIDELINES",
    "CODEX_TOOL_USAGE",
    "CODEX_WORKFLOW",
    "CODEX_ENVIRONMENT_TEMPLATE",
]
